row.names<-c("R1","R2","R3")
col.names<-c("C1","C2","C3","C4")
mat.names<-c("M1","M2")
A<-array(1:24,dim=c(3,4,2),dimnames=list(row.names,col.names,mat.names))
print(A)
ROW1<-sum(A["R1",,"M1"])+sum(A["R1",,"M2"])
print (ROW1)
ROW2<-sum(A["R2",,"M1"])+sum(A["R2",,"M2"])
print (ROW2)
ROW3<-sum(A["R3",,"M1"])+sum(A["R3",,"M2"])
print (ROW3)