row.names<-c("D1","D2","D3","D4")
col.names<-c("Male","Female")
mat.names<-c("Tamilnadu","Telangana")
A<-array(seq(5000,10000,by=500),dim = c(4,2,2),dimnames = list(row.names,col.names,mat.names))
print (A)
maximum=max(apply(A,c(1),max))
minmale=min(apply(A,c(2),min))
print(maximum)
print(minmale)